### ISSUE TITLE
User can search for new jokes

### ISSUE THREAD

**Issue by michelleschofield** [michelleschofield/wisecrack#1]
## ⚙️ Feature

User will be able to search for jokes
## 📐 Functionality

User can select certain inputs to get certain jokes
## 🖼️ Wireframes

<img width="677" alt="Screenshot 2024-09-30 at 12 25 12 PM" src="https://github.com/user-attachments/assets/1d170a93-34c2-4a79-81c2-2197e9e0b8ad">
<img width="274" alt="Screenshot 2024-09-30 at 12 25 38 PM" src="https://github.com/user-attachments/assets/3ca33404-eda6-48fc-a744-5fc3b26d1b61">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create html for the header at the top of the screen
- [x] Create divs to hold each view
- [x] Build form for search parameters
  - [x] a text input for searching for a string inside the jokes
  - [x] radio buttons for type being single or two-part or both
  - [x] checkboxes for categories
  - [x] new jokes button
- [x] Create text for when there are no jokes that match the search terms
- [x] Add a submit event listener to the form
  - [x] get the data from the form
    - [x] get string from contains text input
    - [x] get type from radio buttons
    - [x] get values of all checked category boxes in a string with categories separated by commas
    - [x] put all of them in an object 
  - [x] define function to assemble the url for the fetch request
    - [x] start with "https://v2.jokeapi.dev/joke/"
    - [x] add categories
    - [x] add queries for safe-mode, type, and amount
- [x] Define a function that will render each joke
  - [x] check if single or two-part
    - [x] one p element for single and two for two-part
  - [x] one star button for favorite
  - [x] one plus button for adding to the collection
- [x] Loop through jokes to render each one
- [x] If there are jokes hide the no jokes text, show it if there are jokes
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
