### ISSUE TITLE
User can unfavorite a joke

### ISSUE THREAD

**Issue by michelleschofield** [michelleschofield/wisecrack#11]
## ⚙️ Feature

User can click on star button to mark a joke as no favorite
## 📐 Functionality

User can click on star button to mark a joke as no longer a favorite

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="379" alt="Screenshot 2024-10-03 at 11 19 33 AM" src="https://github.com/user-attachments/assets/30555a01-cec2-457c-9289-f2b1daa80370">
<img width="605" alt="Screenshot 2024-10-03 at 11 19 52 AM" src="https://github.com/user-attachments/assets/86cbe43b-71b4-4ce0-86ef-17518892dde2">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] in handle click add detection for when the faved button is clicked
- [x] define a function unFavorite that takes the card as a parameter
  - [x] get the faved button element 
  - [x] pass the faved button to changeToHollowFav
  - [x] remove the data-favorite attribute from the card
  - [x] find the joke object in data and assign it to a variable
  - [x] remove the favorite property from the object
  - [x] determine in which view the button was clicked
  - [x] if it is in the collection move it to the bottom
  - [x] do a query selector on the opposite view to determine if there a card there that needs to be updated and if there is
    - [x] change the styling on the star button
    - [x] remove the data-favorite attribute
    - [x] move it to the bottom if it was unfavorited from the search view
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
