### ISSUE TITLE
User can add jokes to their collection

### ISSUE THREAD

**Issue by michelleschofield** [michelleschofield/wisecrack#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can add jokes to their collection
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can click the plus button to add a joke to the collection and view the collection by clicking on the tab
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="280" alt="Screenshot 2024-09-30 at 12 28 50 PM" src="https://github.com/user-attachments/assets/6ff36360-7af7-49b0-97bc-5cab311e8514">
<img width="670" alt="Screenshot 2024-09-30 at 12 29 15 PM" src="https://github.com/user-attachments/assets/5a5adeeb-a93e-42ce-85da-c83cd7dd0692">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add event listener jokes-container for click
  - [x] update renderJoke to add data properties with joke info such as id and category and type
  - [x] update renderJoke to check if a joke is already in the collection and change the add button to added if so
  - [x] check to see if the target was the add button
    - [x] check to see if joke isn't already in collection
    - [x] add the joke to the collection
    - [x] update the joke card to show a checkmark instead of the plus
  - [x] define functions in data.ts to read and write the collection to local storage
  - [x] define the collection with readData 
  - [x] write the collection to local storage every time it's updated
  - [x] implement view swapping to be able to look at the collection
  - [x] update renderJoke to allow for one version for the search screen and another for the collection
- **Clean Up**
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
