### ISSUE TITLE
User can remove jokes from their collection

### ISSUE THREAD

**Issue by michelleschofield** [michelleschofield/wisecrack#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can click the trash button to remove a joke from their collection
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can click the trash button to remove a joke from their collection
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="670" alt="Screenshot 2024-09-30 at 1 46 01 PM" src="https://github.com/user-attachments/assets/5a41d80a-89cb-4a57-be74-37a130ca6665">
<img width="280" alt="Screenshot 2024-09-30 at 1 46 19 PM" src="https://github.com/user-attachments/assets/822a9aaf-2555-44f6-8b50-32c0e8386e9b">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Update renderJoke to render a trash button instead of an x button
- [x] create a dialog that will pop up when a user clicks the delete button
  - [x] it will have text that asks if the user is sure
  - [x] a cancel button
  - [x] a confirm button
- [x] when the user clicks confirm
  - [x] the dialog is closed
  - [x] the card is removed the collection view
  - [x] the joke is removed from data and local storage is updated 
  - [x] the search view is checked to see if it contains the joke that was removed and if so the check button is changed to the add button
- [x] when the user clicks cancel the dialog is closed
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
