### ISSUE TITLE
User can mark jokes as favorites

### ISSUE THREAD

**Issue by michelleschofield** [michelleschofield/wisecrack#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can click a star to mark a joke as favorite and it will appear at the top of the collection 
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can click a star to mark a joke as favorite and it will appear at the top of the collection 
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="590" alt="Screenshot 2024-09-30 at 1 50 16 PM" src="https://github.com/user-attachments/assets/07bd6707-8eaf-47f8-b589-c51f95c4538b">
<img width="276" alt="Screenshot 2024-09-30 at 1 50 37 PM" src="https://github.com/user-attachments/assets/287df03c-2e6b-46a5-8fde-e63afd24f934">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] When a user clicks the star button 
  - [x] the background color will change to gold
  - [x] if the joke is not already in the collection it is added
  - [x] the joke will appear at the top of the collection
  - [x] local storage is updated to show that joke as favorite
- [x] when the collection is first rendered favorites appear at the top
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
