### ISSUE TITLE
User can sort the jokes in their collection

### ISSUE THREAD

**Issue by michelleschofield** [michelleschofield/wisecrack#6]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can select which category of jokes they'd like to view
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can select which category of jokes they'd like to view
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] add a select to the top of the collection
- [x] define a function renderCategory
  - [x] function will loop through the collection
  - [x] will render the joke only if the category matches the selected category
- [x] make it look passable
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
